version: '3.8'
services:
  expense-frontend:
    build:
      context: ./expense-frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - expense-backend
  expense-backend:
    build:
      context: ./expense-backend
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  # webserver:
  #   image: nginx:alpine
  #   restart: always
  #   ports:
  #     - "81:80"
  #     - "8000:8000"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - expense-frontend
  #     - expense-backend

  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "8000:8000"
