version: "3.3"
services:
  expense-frontend:
    build:
      context: ./expense-frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - expense-backend
  expense-backend:
    build:
      context: ./expense-backend
      dockerfile: Dockerfile
    restart: always
  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "8000:8000"